# Generated by Django 6.0.4 on 2026-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
