# Generated by Django 6.0.4 on 2026-04-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0003_alter_flight_airplane_alter_flight_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport_app.order'),
            preserve_default=False,
        ),
    ]
