# Generated by Django 6.0.4 on 2026-04-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0010_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airplanes', to='airport_app.airplanetype'),
        ),
    ]
