# Generated by Django 6.0.4 on 2026-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0012_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='airplanetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
