# Generated by Django 6.0.4 on 2026-04-23 10:19

import airport_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0013_alter_airplane_name_alter_airplanetype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('seat',)},
        ),
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_app.models.airplane_image_path),
        ),
    ]
